# https://taskfile.dev

version: '3'

dotenv: ['.env']
vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task: build
  build:
    cmds:
      - npm run build
  test:
    cmds:
      - jest
